# SITE CONFIGURATION
title: The MycoBlog # your site title
author: shanebweaver # You :P
description: > # Meta description of Homepage
  Thoughts on Amateur Mycology and Engineering from the mind of Washingtonian local, Shane Weaver.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://www.mycoblog.com" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Shane Weaver
  links:
    - https://www.facebook.com/shane.weaver
    - https://www.linkedin.com/in/shanebweaver/
    - https://github.com/shanebweaver

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Connect', link: '/contact'}

tagline: >
  Thoughts on Amateur Mycology and Engineering

hero_img: posts/various.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: shanebweaver@gmail.com # email for form submission

# twitter_username: ShaneWe94191747 # replace with your_twitter_username or comment to remove link from footer
github_username:  shanebweaver # replace with your_github_username or comment to remove link from footer
instagram_username: shanebweaver # replace with your_instagram_username or comment to remove link from footer
# linkedin_username: shanebweaver

disqus:
  shortname: mycoblog # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
